<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


    <!-- Including files -->

    <!-- Inertial -->
    <xacro:include filename="macro/inertial.xacro" />

    <!-- Wheel -->
    <xacro:include filename="macro/wheel.xacro" />


    <!-- Define robot constants -->

    <!-- Robot base constants -->
    <xacro:property name="base_width" value="0.5" />
    <xacro:property name="base_length" value="0.8" />
    <xacro:property name="base_height" value="0.15" />

    <!-- Robot wheels constants -->
    <xacro:property name="wheel_radius" value="0.05" />
    <xacro:property name="wheel_width" value="0.04" />
    <xacro:property name="wheel_ygap" value="-0.005" />
    <xacro:property name="wheel_zoff" value="0.05" />
    <xacro:property name="wheel_xoff" value="0.00" />

    <!-- Castor wheels constats -->
    <xacro:property name="caster_xoff" value="0.14" />


    <!-- Robot Base -->
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <material name="white">
                <color rgba="1.0 1.0 1.0 1.0" />
            </material>
        </visual>

        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
        </collision>

        <xacro:box_inertia mass="15" width="${base_width}" length="${base_length}"
            height="${base_height}" />
    </link>

    <gazebo reference="base_link">
        <material>Gazebo/White</material>
    </gazebo>


    <!-- Robot Footprint -->
    <link name="base_footprint" />

    <joint name="base_joint" type="fixed">
        <parent link="base_link" />
        <child link="base_footprint" />
        <origin xyz="0.0 0.0 ${-(wheel_radius+wheel_zoff)}" rpy="0 0 0" />
    </joint>


    <!-- Wheels -->
    <xacro:wheel prefix="left_wheel_1" x="0.3" y="0.233" x_reflect="-1" y_reflect="1" />
    <xacro:wheel prefix="right_wheel_1" x="0.3" y="0.233" x_reflect="-1" y_reflect="-1" />

    <xacro:wheel prefix="left_wheel_2" x="0" y="0.233" x_reflect="-1" y_reflect="1" />
    <xacro:wheel prefix="right_wheel_2" x="0" y="0.233" x_reflect="-1" y_reflect="-1" />

    <xacro:wheel prefix="left_wheel_3" x="-0.3" y="0.233" x_reflect="-1" y_reflect="1" />
    <xacro:wheel prefix="right_wheel_3" x="-0.3" y="0.233" x_reflect="-1" y_reflect="-1" /> 


</robot>